# @see https://github.com/rtCamp/action-wordpress-org-plugin-deploy

name: Deploy to WordPress.org
on:
  push:
    tags:
      - '*'
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: WordPress Plugin Deploy
        env:
          CUSTOM_COMMAND: composer install
          CUSTOM_PATH: src
          ASSETS_DIR: assets
          SLUG: bh-wc-set-gateway-by-url
          WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
          WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
        run: chmod +x ./.github/deploy.sh && ./.github/deploy.sh
