# @see https://github.com/rtCamp/action-wordpress-org-plugin-deploy

name: Deploy to WordPress.org
on:
  push:
    tags:
      - '*'
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Composer install
        uses: php-actions/composer@v1

      - name: Deploy
        run: chmod +x ./.github/deploy.sh && ./.github/deploy.sh
        env:
          SVN_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
